FROM nginx:latest

WORKDIR /usr/share/nginx/html



RUN echo "VIDEO YOUTUBE - WORKSHOP DOCKER <br>" > index.html

RUN echo "<iframe width='560' height='315' src='https://www.youtube.com/embed/J4NnmbbSizQ?start=50' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>" >> index.html

EXPOSE 80
