version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - /root/docker/example11-DockerComposeMysql/db_mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_teste01
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste@123
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
volumes:
  db_mysql:
    driver: local
